{"artifact": "materiais/quinto-post/index.html", "exception": "AssertionError", "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/lektor/builder.py\", line 800, in update\n    yield ctx\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/lektor/builder.py\", line 1070, in build_artifact\n    build_func(artifact)\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/lektor/build_programs.py\", line 182, in build_artifact\n    artifact.render_template_into(\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/lektor/builder.py\", line 653, in render_template_into\n    rv = self.build_state.env.render_template(\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/lektor/environment.py\", line 542, in render_template\n    return self.jinja_env.get_or_select_template(name).render(ctx)\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/jinja2/environment.py\", line 1090, in render\n    self.environment.handle_exception()\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/jinja2/environment.py\", line 832, in handle_exception\n    reraise(*rewrite_traceback_stack(source=source))\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/jinja2/_compat.py\", line 28, in reraise\n    raise value.with_traceback(tb)\n  File \"/home/gilberto/Dropbox/IdeasPaper/sinar/extensao/R-pandemia/curso/templates/materiais.html\", line 1, in top-level template code\n    {% extends \"layout.html\" %}\n  File \"/home/gilberto/Dropbox/IdeasPaper/sinar/extensao/R-pandemia/curso/templates/layout.html\", line 45, in top-level template code\n    {% block body %}{% endblock %}\n  File \"/home/gilberto/Dropbox/IdeasPaper/sinar/extensao/R-pandemia/curso/templates/materiais.html\", line 3, in block \"body\"\n    <p> Publicando por <em>{{ this.author }}</em> em <em>{{ this.pub_date|dateformat('full') }} </em>.</p>\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/lektor/environment.py\", line 83, in new_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/babel/dates.py\", line 708, in format_date\n    return pattern.apply(date, locale)\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/babel/dates.py\", line 1240, in apply\n    return self % DateTimeFormat(datetime, locale)\n  File \"/usr/local/lib/lektor/lib/python3.9/site-packages/babel/dates.py\", line 1246, in __init__\n    assert isinstance(value, (date, datetime, time))\nAssertionError"}
